init:
  - git config --global core.autocrlf 
environment:
  xamarin_email: 'naveensrinivasan@yahoo.com'
  xamarin_password: 'password'
before_build:
- ps: >-
    Register-XamarinLicense -Email $env:xamarin_email -Password $env:xamarin_password -Product iOS

    Register-XamarinLicense -Email $env:xamarin_email -Password $env:xamarin_password -Product Android
build:
  project: Octokit-XamarinStudio.sln
  verbosity: minimal
after_build:
- ps: Unregister-XamarinLicense -Email $env:xamarin_email -Password $env:xamarin_password
on_finish: []
